### ISSUE TITLE
BUG about the dataset

### ISSUE THREAD

**Issue by ShenAoChen2001** [chenyuwuxin/EulerNet#1]
I have downloaded the avazu from the superlink in your github https://www.kaggle.com/c/avazu-ctr-prediction/data?select=train.gz.

then i run avazu_parse.py

the error appeared

**Comment by ShenAoChen2001** [comment]
![Uploading 1711282484557.jpg…]()

**Comment by ShenAoChen2001** [comment]
D:\anaconda3\envs\dl\python.exe "D:\pycharm\PyCharm 2022.1.4\plugins\python\helpers\pydev\pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 59523 --file C:/Users/14760/Desktop/Code/EulerNet-main/DataSource/avazu_parse.py
Connected to pydev debugger (build 221.6008.17)
100%|██████████| 100/100 [01:24<00:00,  1.19it/s]
  9%|▊         | 2/23 [01:38<17:12, 49.19s/it]
Traceback (most recent call last):
  File "D:\pycharm\PyCharm 2022.1.4\plugins\python\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\pycharm\PyCharm 2022.1.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/14760/Desktop/Code/EulerNet-main/DataSource/avazu_parse.py", line 67, in <module>
    for key, val in lst.items():
RuntimeError: dictionary changed size during iteration

**Comment by Ethan-TZ** [comment]
@ShenAoChen2001 
Hello, thanks for your attention to my work. It's possible that the version of the dataset you downloaded is incorrect. I have shared my source files, and you can download them from the following link. 
[Avazu](https://drive.google.com/file/d/1_itJLn7sRW7NDTd6C2Jx-qDDEWDlXqx7/view?usp=drive_link)

**Comment by ShenAoChen2001** [comment]
thanks for your reply，the bug is not be solved，because the code
  for lst in tqdm(feat_list):
    idx = 1
    for key, val in lst.items():
      if val < thres:
        del lst[key]
      else:
        lst[key] = idx
        idx += 1

you delete the element.

I want to know can you run avazu_parse.py in your enviroment?

**Comment by ShenAoChen2001** [comment]
> @ShenAoChen2001 Hello, thanks for your attention to my work. It's possible that the version of the dataset you downloaded is incorrect. I have shared my source files, and you can download them from the following link. [Avazu](https://drive.google.com/file/d/1_itJLn7sRW7NDTd6C2Jx-qDDEWDlXqx7/view?usp=drive_link)

thanks for your reply，the bug is not be solved，because the code
for lst in tqdm(feat_list):
idx = 1
for key, val in lst.items():
if val < thres:
del lst[key]
else:
lst[key] = idx
idx += 1

you delete the element.

I want to know can you run avazu_parse.py in your enviroment?

**Comment by Ethan-TZ** [comment]
@ShenAoChen2001 Yes, we follow the [FmFM's script](https://github.com/yahoo/FmFM/blob/main/data/avazu/trans_avazu_dataset.py) to process the dataset.

**Comment by ShenAoChen2001** [comment]
> @ShenAoChen2001 Yes, we follow the [FmFM's script](https://github.com/yahoo/FmFM/blob/main/data/avazu/trans_avazu_dataset.py) to process the dataset.

好吧，我再看看咋回事。我还有一个问题python train.py --config_files=[dataset].yaml这句话里面的yaml文件是metaData文件里面的yaml么。

**Comment by Ethan-TZ** [comment]
@ShenAoChen2001 Yes. Additionally, I provide the processed dataset download at [Here](https://drive.google.com/file/d/1XU-8Zr2gh6Kx6U5c0yKlgAd8OA6ovM_x/view?usp=drive_link). You should put it into the /Cache folder, and run the code.
